# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Debugging with ssh
      # You may pin to the exact commit or the version.
      # uses: lhotari/action-upterm@d23c2722bdab893785c9fbeae314cbf080645bd7
      uses: lhotari/action-upterm@v1
      with:
        # Github Token
        GITHUB_TOKEN: # optional, default is ${{ github.token }}
        # If only the public SSH keys of the user triggering the workflow should be authorized
        limit-access-to-actor: # optional, default is false
        # If only the public SSH keys of the listed GitHub users should be authorized
        limit-access-to-users: # optional, default is 
        # upterm server address (required), supported protocols are ssh, ws, or wss.
        upterm-server: # default is ssh://uptermd.upterm.dev:22
        # Content for ~/.ssh/known_hosts file on the server
        ssh-known-hosts: # optional, default is upterm-server
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
